<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="6" hostname="Asra" failures="1" tests="1" name="Default test(failed)" time="0.043" errors="0" timestamp="2024-07-09T23:07:28 EDT">
  <testcase classname="testNGDemo.testscenario1" name="first_testcase" time="0.008">
    <failure type="java.lang.AssertionError" message="expected [hello world] but found [hello]">
      <![CDATA[java.lang.AssertionError: expected [hello world] but found [hello]
at testNGDemo.testscenario1.first_testcase(testscenario1.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- first_testcase -->
  <testcase classname="testNGDemo.testscenario1" name="seventh_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- seventh_testcase -->
  <testcase classname="testNGDemo.testscenario1" name="sixth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- sixth_testcase -->
  <testcase classname="testNGDemo.testscenario1" name="third_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- third_testcase -->
  <testcase classname="testNGDemo.testscenario1" name="fourth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- fourth_testcase -->
  <testcase classname="testNGDemo.testscenario1" name="second_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- second_testcase -->
  <testcase classname="testNGDemo.testscenario1" name="fifth_testcase" time="0.0">
    <ignored/>
  </testcase> <!-- fifth_testcase -->
</testsuite> <!-- Default test(failed) -->
